### ISSUE TITLE
Lumia 830

### ISSUE THREAD

**Issue by robixxx1** [artyom-beilis/skyhopper#1]
Dear Artyom,

I've some problem with an old lumia 830 windows phone... it's seems that the applet doesn't use the compass sensors because I always found the "no compass available" symbol up right on the screen...

**Comment by artyom-beilis** [comment]
What browser do you use? Not all browsers provide compass information. For example Firefox does not. Webkit based browsers do like Safari, Chrome.

If compass is missing you can drag screen left/right to the expected direction to match the azimuth with the expected one and than align. Once you are aligned both axis should be working automatically since it switches to gyro once aligned.

I find myself frequently switch to manual mode due to poor compass accuracy in general, so also it may be less convenient it should not affect general functionality and accuracy (as long as you have good working sensors) 

I'd like to know actual field experience with the windows phone.

**Comment by robixxx1** [comment]
Dear Artyom, I know that no one use windows phone anymore, could be I'm the
last one, but on my windows phone i can only use edge for browser, there is
no  alternatives. i can infact drag the screen to align, but once aligned,
for example if I turn 90° to the right, on the display the azimuth change
only 10°... I also cannot switch to manual mode because the iconis fixed on
the "no compas available! status...  But I switch on the android smartphone
fo my wife, and all is working perfectly!

Roberto

Il giorno lun 3 mag 2021 alle ore 21:24 Artyom Beilis <
***@***.***> ha scritto:

**Comment by artyom-beilis** [comment]
> f I turn 90° to the right, on the display the azimuth change
only 10°.

I assume you turn it to the right when it is flat on table yes? If so, the gyro in the phone isn't working. If the senors do not work there is nothing I can do.

You can put it flat on surface reload app and see in settings the value of alpha (last row) turn it 90 degree and see if alpha is changed by ~90 degrees.

> I also cannot switch to manual mode because the icon is fixed on the "no compass available!" status.

This is same situation as in Firefox.

Manual/Compass mode can be switched when browser provides compass information. In any case if you have working gyro than you can use it without compass as well. But since gyro does not work than there is nothing I can do.

**Comment by robixxx1** [comment]
All clear now, thank you very much! So I think I will go on with android, at least unless I found a compatible browser for my windows phone...

**Comment by artyom-beilis** [comment]
> All clear now, thank you very much! So I think I will go on with android, at least unless I found a compatible browser for my windows phone...

I don't think it is browser problem but rather gyro quality issue

**Comment by artyom-beilis** [comment]
Likely HW issue
